"""add category type constraint

Revision ID: 7aceacdbab8a
Revises: c81da9934120
Create Date: 2026-08-12 02:25:34.696489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aceacdbab8a'
down_revision: Union[str, Sequence[str], None] = 'c81da9934120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('check_category_type', 'categories', "type IN ('income', 'expense')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_category_type', 'categories', type_='check')
    # ### end Alembic commands ###
